# Generated by Django 5.2.9 on 2026-01-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0012_emailreputation_ipreputation_voteauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('unique_voters', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='Event.event')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['event', 'date'], name='Analytics_a_event_i_f6537c_idx')],
                'unique_together': {('event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ContestantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vote_rank', models.IntegerField(blank=True, null=True)),
                ('percentage_of_total', models.FloatField(default=0.0)),
                ('votes_in_last_hour', models.IntegerField(default=0)),
                ('votes_in_last_24_hours', models.IntegerField(default=0)),
                ('momentum', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contestant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Event.eventcategorycontestant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_analytics', to='Event.event')),
            ],
            options={
                'ordering': ['-total_votes'],
                'indexes': [models.Index(fields=['event', 'total_votes'], name='Analytics_c_event_i_b70284_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=50)),
                ('browser_type', models.CharField(blank=True, max_length=50)),
                ('os_type', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('session_duration', models.IntegerField(default=0)),
                ('pages_visited', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='Event.event')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_data', to='Event.vote')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'device_type'], name='Analytics_d_event_i_2350d1_idx'), models.Index(fields=['event', 'country'], name='Analytics_d_event_i_3cce6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('unique_voters', models.IntegerField(default=0)),
                ('total_vote_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_vote_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completed_payments', models.IntegerField(default=0)),
                ('failed_payments', models.IntegerField(default=0)),
                ('pending_payments', models.IntegerField(default=0)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('views', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration', models.IntegerField(default=0)),
                ('flagged_votes', models.IntegerField(default=0)),
                ('quarantined_votes', models.IntegerField(default=0)),
                ('fraud_detection_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Event.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'updated_at'], name='Analytics_e_event_i_1926f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoteTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('unique_voters', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_votes_per_voter', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_time_series', to='Event.event')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['event', 'timestamp'], name='Analytics_v_event_i_b3b6d2_idx'), models.Index(fields=['timestamp'], name='Analytics_v_timesta_b7a097_idx')],
            },
        ),
    ]
