# Generated by Django 5.2.9 on 2026-01-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
