# Generated by Django 5.2.9 on 2026-01-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
    ]
