# Generated by Django 5.2.9 on 2025-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
