# Generated by Django 5.2.9 on 2026-01-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_eventcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCategories',
            new_name='EventCategory',
        ),
    ]
