# Generated by Django 5.2.9 on 2026-01-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_eventcategorycontestant_eventcategory_contestants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'amount_per_vote', 'banner', 'start_time', 'end_time')},
        ),
    ]
