# Generated by Django 5.2.9 on 2026-01-25 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_alter_event_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='contestants',
        ),
        migrations.RemoveField(
            model_name='eventcategorycontestant',
            name='event',
        ),
        migrations.AddField(
            model_name='eventcategorycontestant',
            name='hobby',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='amount_per_vote',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='eventcategorycontestant',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='eventcategorycontestant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='Event.eventcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('creator', 'name', 'start_time', 'end_time', 'bio')},
        ),
    ]
