# Generated by Django 5.2.9 on 2026-01-26 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_alter_event_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.GenericIPAddressField()),
                ('voter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vote_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='Event.eventcategorycontestant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='Event.event')),
            ],
            options={
                'unique_together': {('contestant', 'voter_ip', 'voter_email')},
            },
        ),
    ]
