# Generated by Django 5.2.9 on 2026-01-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReputation',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_free_email', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPReputation',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False, unique=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('abuse_score', models.IntegerField(default=0)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_vpn', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vote_created', 'Vote Created'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('vote_verified', 'Vote Verified'), ('vote_flagged', 'Vote Flagged'), ('vote_quarantined', 'Vote Quarantined'), ('vote_approved', 'Vote Approved'), ('vote_rejected', 'Vote Rejected'), ('fraud_detected', 'Fraud Detected'), ('manual_review', 'Manual Review')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vote Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteFraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('risk_score', models.IntegerField(default=0)),
                ('fraud_flags', models.JSONField(blank=True, default=list)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('velocity_check_passed', models.BooleanField(default=True)),
                ('behavioral_check_passed', models.BooleanField(default=True)),
                ('geographic_check_passed', models.BooleanField(default=True)),
                ('ip_reputation_passed', models.BooleanField(default=True)),
                ('email_reputation_passed', models.BooleanField(default=True)),
                ('request_signature', models.CharField(blank=True, max_length=255)),
                ('vote_integrity_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='number_of_votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vote',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_ip', 'event'], name='Event_vote_voter_i_3c73ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_email', 'event'], name='Event_vote_voter_e_ddcf43_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['contestant', 'created_at'], name='Event_vote_contest_553e1d_idx'),
        ),
        migrations.AddField(
            model_name='voteauditlog',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='Event.vote'),
        ),
        migrations.AddField(
            model_name='votefrauddetection',
            name='vote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_detection', to='Event.vote'),
        ),
        migrations.AddIndex(
            model_name='voteauditlog',
            index=models.Index(fields=['vote', 'created_at'], name='Event_votea_vote_id_a65750_idx'),
        ),
        migrations.AddIndex(
            model_name='voteauditlog',
            index=models.Index(fields=['action', 'created_at'], name='Event_votea_action_7ef931_idx'),
        ),
        migrations.AddIndex(
            model_name='votefrauddetection',
            index=models.Index(fields=['risk_score'], name='Event_votef_risk_sc_03101e_idx'),
        ),
        migrations.AddIndex(
            model_name='votefrauddetection',
            index=models.Index(fields=['is_suspicious'], name='Event_votef_is_susp_75e624_idx'),
        ),
        migrations.AddIndex(
            model_name='votefrauddetection',
            index=models.Index(fields=['is_quarantined'], name='Event_votef_is_quar_6b6e34_idx'),
        ),
    ]
