# Generated by Django 5.2.9 on 2026-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_extendeduser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='verification_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
