# Generated by Django 5.2.9 on 2026-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_extendeduser_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email_verification_token_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
