"""
Django settings for PageantryVoting project.

Generated by 'django-admin startproject' using Django 6.0.

For more information:
https://docs.djangoproject.com/en/6.0/topics/settings/
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
 

# ---------------------------
# BASE DIRECTORY
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# SECURITY
# ---------------------------
SECRET_KEY = 'django-insecure-=qugfqweat5f_0fc+s6=yeolooyugs%g6=&m5bk*0^s1-=s(h$'
DEBUG = True
ALLOWED_HOSTS = [
    # '192.168.1.100',
    # 'localhost',
    # '127.0.0.1',
    # '10.187.99.190'
    '*'
]

# ---------------------------
# APPLICATIONS
# ---------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'corsheaders',
    "rest_framework_simplejwt.token_blacklist",
    # Local apps
    'Auth',
    # 'Home',
    'Event',
    'Analytics',
    # rest_framework
    'rest_framework',
]
SITE_ID = 1

# Use your custom user model
# settings.py
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Auth.ExtendedUser'

# ---------------------------
# MIDDLEWARE
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'allauth.account.middleware.AccountMiddleware',
 
]
# ---------------------------
# URLS AND TEMPLATES
# ---------------------------
ROOT_URLCONF = 'PageantryVoting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PageantryVoting.wsgi.application'

# ---------------------------
# DATABASE
# ---------------------------
DATABASES = {
    'default': {
     'ENGINE': 'django.db.backends.sqlite3',
     'NAME': BASE_DIR /'db.sqlite3'
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'PageantryVotingDb',
        # 'USER': 'postgres',
        # 'PASSWORD': '1234',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}

# ---------------------------
# PASSWORD VALIDATION
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ---------------------------
# INTERNATIONALIZATION
# ---------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------
# STATIC FILES
# ---------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# ---------------------------
# REST_FRAMEWORK SETTINGS 
# ---------------------------

MEDIA_URL = '/media/'
MEDIA_ROOT =  BASE_DIR / 'media'


#  --------------------------
# REACT CROSS ORIGIN REQUEST SETTINGS
# ---------------------------

CORS_ALLOWED_ORIGINS =[
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://192.168.1.100:5173',
    'http://10.187.99.190:5173',
    
]
CORS_ALLOW_CREDENTIALS = True



# ------------------------
# CSRF SETTINGS
# ------------------------
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
   
]


# -------------------------------------------------------

# REST Framework + JWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (

        "rest_framework_simplejwt.authentication.JWTAuthentication",

         "rest_framework.authentication.SessionAuthentication",
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ---------------------------
# EMAIL CONFIGURATION (Brevo)
# ---------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '9ed984001@smtp-brevo.com'
EMAIL_HOST_PASSWORD = 'xsmtpsib-9a37ab1729cf6faa414d3d1ed193c6086e3a83dc43f692487f80f8c0f8f28dee-UBQUJuBb9aI7xMRA'
DEFAULT_FROM_EMAIL = 'nanayawfreduah@gmail.com'

# ---------------------------
# FRONTEND CONFIGURATION
# ---------------------------
FRONTEND_URL = 'http://localhost:5173'
PHONE_VERIFICATION_URL = 'http://10.187.99.190:5173/'




# IMAGE AND FILE UPLOAD LIMIT
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024   # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
